name: pantrygo
description: "PantryGo - Stock Your Kitchen in a Few Taps"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  badges: ^3.1.2

  # Navigation
  go_router: ^14.2.0

  # Firebase & Push Notifications (temporarily disabled for testing)
  # firebase_core: ^2.31.0
  # firebase_messaging: ^14.9.2
  # flutter_local_notifications: ^17.2.1+2

  # Payment Integration (temporarily disabled for testing)
  # razorpay_flutter: ^1.3.7

  # Maps & Location (temporarily disabled for testing)
  # google_maps_flutter: ^2.6.1
  # geolocator: ^12.0.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
