// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PantryGo.Api.Data;

#nullable disable

namespace PantryGo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225183316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryPartnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DeliveryPartnerId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = "Fruits",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(5222),
                            Description = "Crisp and sweet red apples",
                            ImageUrl = "/images/products/apples.jpg",
                            IsActive = true,
                            Name = "Fresh Apples",
                            Price = 120.00m,
                            Stock = 100,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = "Fruits",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6819),
                            Description = "Ripe yellow bananas",
                            ImageUrl = "/images/products/bananas.jpg",
                            IsActive = true,
                            Name = "Bananas",
                            Price = 40.00m,
                            Stock = 150,
                            Unit = "dozen"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = "Fruits",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6841),
                            Description = "Juicy oranges rich in Vitamin C",
                            ImageUrl = "/images/products/oranges.jpg",
                            IsActive = true,
                            Name = "Oranges",
                            Price = 80.00m,
                            Stock = 80,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = "Fruits",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6859),
                            Description = "Sweet Alphonso mangoes",
                            ImageUrl = "/images/products/mangoes.jpg",
                            IsActive = true,
                            Name = "Mangoes",
                            Price = 200.00m,
                            Stock = 50,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = "Fruits",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6862),
                            Description = "Fresh green seedless grapes",
                            ImageUrl = "/images/products/grapes.jpg",
                            IsActive = true,
                            Name = "Grapes",
                            Price = 90.00m,
                            Stock = 60,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111201"),
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6865),
                            Description = "Fresh red tomatoes",
                            ImageUrl = "/images/products/tomatoes.jpg",
                            IsActive = true,
                            Name = "Tomatoes",
                            Price = 30.00m,
                            Stock = 200,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111202"),
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6868),
                            Description = "Fresh onions",
                            ImageUrl = "/images/products/onions.jpg",
                            IsActive = true,
                            Name = "Onions",
                            Price = 35.00m,
                            Stock = 300,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111203"),
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6872),
                            Description = "Farm fresh potatoes",
                            ImageUrl = "/images/products/potatoes.jpg",
                            IsActive = true,
                            Name = "Potatoes",
                            Price = 25.00m,
                            Stock = 250,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111204"),
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6879),
                            Description = "Fresh green spinach leaves",
                            ImageUrl = "/images/products/spinach.jpg",
                            IsActive = true,
                            Name = "Spinach",
                            Price = 20.00m,
                            Stock = 100,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111205"),
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6883),
                            Description = "Crunchy orange carrots",
                            ImageUrl = "/images/products/carrots.jpg",
                            IsActive = true,
                            Name = "Carrots",
                            Price = 45.00m,
                            Stock = 120,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111301"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6886),
                            Description = "Fresh full cream milk",
                            ImageUrl = "/images/products/milk.jpg",
                            IsActive = true,
                            Name = "Milk",
                            Price = 60.00m,
                            Stock = 200,
                            Unit = "liter"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111302"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6890),
                            Description = "Creamy salted butter",
                            ImageUrl = "/images/products/butter.jpg",
                            IsActive = true,
                            Name = "Butter",
                            Price = 55.00m,
                            Stock = 80,
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111303"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6895),
                            Description = "Processed cheese slices",
                            ImageUrl = "/images/products/cheese.jpg",
                            IsActive = true,
                            Name = "Cheese",
                            Price = 120.00m,
                            Stock = 60,
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111304"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6900),
                            Description = "Fresh plain yogurt",
                            ImageUrl = "/images/products/yogurt.jpg",
                            IsActive = true,
                            Name = "Yogurt",
                            Price = 45.00m,
                            Stock = 100,
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111305"),
                            Category = "Dairy",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6913),
                            Description = "Fresh cottage cheese",
                            ImageUrl = "/images/products/paneer.jpg",
                            IsActive = true,
                            Name = "Paneer",
                            Price = 90.00m,
                            Stock = 70,
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111401"),
                            Category = "Snacks",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6917),
                            Description = "Crispy salted potato chips",
                            ImageUrl = "/images/products/chips.jpg",
                            IsActive = true,
                            Name = "Potato Chips",
                            Price = 30.00m,
                            Stock = 150,
                            Unit = "pack"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111402"),
                            Category = "Snacks",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6921),
                            Description = "Cream filled biscuits",
                            ImageUrl = "/images/products/biscuits.jpg",
                            IsActive = true,
                            Name = "Biscuits",
                            Price = 25.00m,
                            Stock = 200,
                            Unit = "pack"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111403"),
                            Category = "Snacks",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6924),
                            Description = "Mixed crunchy namkeen",
                            ImageUrl = "/images/products/namkeen.jpg",
                            IsActive = true,
                            Name = "Namkeen",
                            Price = 40.00m,
                            Stock = 100,
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111404"),
                            Category = "Snacks",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6928),
                            Description = "Milk chocolate bar",
                            ImageUrl = "/images/products/chocolate.jpg",
                            IsActive = true,
                            Name = "Chocolates",
                            Price = 50.00m,
                            Stock = 120,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111405"),
                            Category = "Snacks",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6932),
                            Description = "Roasted mixed nuts",
                            ImageUrl = "/images/products/nuts.jpg",
                            IsActive = true,
                            Name = "Nuts Mix",
                            Price = 150.00m,
                            Stock = 80,
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111501"),
                            Category = "Beverages",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6936),
                            Description = "Fresh orange juice",
                            ImageUrl = "/images/products/orange-juice.jpg",
                            IsActive = true,
                            Name = "Orange Juice",
                            Price = 80.00m,
                            Stock = 100,
                            Unit = "liter"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111502"),
                            Category = "Beverages",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6941),
                            Description = "Ready to drink cold coffee",
                            ImageUrl = "/images/products/cold-coffee.jpg",
                            IsActive = true,
                            Name = "Cold Coffee",
                            Price = 45.00m,
                            Stock = 120,
                            Unit = "250ml"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111503"),
                            Category = "Beverages",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6944),
                            Description = "Natural coconut water",
                            ImageUrl = "/images/products/coconut-water.jpg",
                            IsActive = true,
                            Name = "Coconut Water",
                            Price = 35.00m,
                            Stock = 150,
                            Unit = "pack"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111504"),
                            Category = "Beverages",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6947),
                            Description = "Organic green tea bags",
                            ImageUrl = "/images/products/green-tea.jpg",
                            IsActive = true,
                            Name = "Green Tea",
                            Price = 120.00m,
                            Stock = 80,
                            Unit = "box"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111505"),
                            Category = "Beverages",
                            CreatedAt = new DateTime(2025, 12, 25, 18, 33, 15, 848, DateTimeKind.Utc).AddTicks(6952),
                            Description = "Sparkling lemon soda",
                            ImageUrl = "/images/products/soda.jpg",
                            IsActive = true,
                            Name = "Soda",
                            Price = 25.00m,
                            Stock = 200,
                            Unit = "can"
                        });
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Address", b =>
                {
                    b.HasOne("PantryGo.Api.Models.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Order", b =>
                {
                    b.HasOne("PantryGo.Api.Models.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PantryGo.Api.Models.Entities.User", "DeliveryPartner")
                        .WithMany("DeliveryAssignments")
                        .HasForeignKey("DeliveryPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PantryGo.Api.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("DeliveryPartner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("PantryGo.Api.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryGo.Api.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PantryGo.Api.Models.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("DeliveryAssignments");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
